dist: trusty
sudo: false

language: scala

scala:
  - 2.12.4
  - 2.11.11

jdk: oraclejdk8

script: sbt ++$TRAVIS_SCALA_VERSION clean coverage test

after_success: 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then sbt ++$TRAVIS_SCALA_VERSION coverageReport coveralls; fi'

notifications:
  slack:
    on_success: never
    on_failure: always
    rooms:
      secure: ZkG0Ru1NcqJdGuf6gesro4xhAwU/zYCrU3FUOksYMtsdhd+SbVwLNXLlcBXZRQmsPKOPfC6McEyO6jc5Y05SXBkTNBzOw8Fe/bxEbBKYnxLQY7QrimfMstDu5Rz7xksNGDGiVxwXR+OtF3ixS6hzCR1rrHDrYmFQ/lPMGU+kyTJ54Vu81CBrhNbbuhswMx2N+QFLQDv090o8PgXa6YJJRo4k2qReQcZ6h7cCMVgfqzuJda/kmShl6HnOU4RjsIT5TLYWobLFdTJzPQdjtpASdwJyu2LAjF72BeO5jlNNp5eufrkRCaFbSt+NEYXV63DQqSb0QrPmur/n8M4RgumReDxNK3wPqrL4TanLsMcmTMEzVt2/GKJvt1HEila9HdLiZBhhDjV5NaekEbMmxh9azwUN2xpP6wlHbe3TkZsnly1r5V62hKePXP61Gatlp1HIXIGvfyLCDDyrvVzy1K+EELi3qDD865xgMJFB8BfRth6DUTzuc46Sqv/Iq03edp6VVUh9LUzrp4pU2BLsjMHU/aii+e5eoeqHLOzTphkZByg07z2zv9Jk27vgR1PO4G+LVV4l3RJVT8bU4mzV5ONX4k9Ss2UGaMQbvtao0hQGAo6XdRDyh3NfJVq/YG+vcDJZjOOsaUxlZRv2XWFpX6eiEu3sxYCz3kscmV0359HDeQ8=
env:
  global:
  - secure: BO9XIMoMUyynd8+ZPPMjbVeDFV8840ykzvM0XEsfOEwf/LF7l1Urq9wyvj9ralfGX2OjkrhZEKeKAZjIec9COOOrA860YaOTEEfn4q1zfPfec3LQkRm9gFrR/yYfOSFJeoMyNChGru7dqb2PSAnxSDcK+MDSrJjtVv6+GqZFEePz9AL49thJ8k0GCarEcQcfXOBnSKdFSEz/lGjO8mu1nrfxL5wYHz1LB/66uQ9oQFWyRV1l4man+5jO3tKOoCq3MR/WM5WvpcVIZgIfgiAhpUIcJxcz1V1JTzwOs/WMLm0mUWqjAC0loK5lWF7x2a1T5WuxRFNsLstu5Rl59d2GNMLr5EfVDWPlDnJkagEIB7rlAtxVeqSp2Fn3oJ1Xis99cFqW/juZ4dIGipfmsVUuRzUxVx5d5h7Z0CzNYlhvjsJTmJVE+vIkOJOTGFOgDpkJiyMWAr2ytARNqdy24jFhje5antKStmRgDIWBI2jKwsE11S/2UQ64rHE0+CHNwmcQJypm/TYZmQAVoiiYDBWPz39ZfIFy22zg9Cymz/6WbiL+kvfEdlfy/thdxk0HK3ihj3aEiNfxbecyySunHjcy0bHZad4BuCu9JWz5xDkch6IYMrDZLh4HyK3aRXgKKPRFVzRua7cZZ1UQk+mqUmzR/yAZWs5MCz+h5QT4dB4o/Ps=
  - secure: C6NtnZM18aiZ3SAuR66P/7HApGS2ALGiKpmQOnS71vTSY0Mr6U+sUmkdv+lcshto36V93O/JSnOFbs3x+a3V+F6SzUmuIBLIFM+e1MHBpHB75EHEnFaF2k1b5rku/ZHL2wDxJsCUk/Hf2RAhrre8AnFgFzmEJpZIK+WZwbpRA8quwZ2i6KPnpLGVwu7Z499aM6FBUiUqZsGJ6/wJSa5au22Sr8zssS0Ok7HW6efQR+dNzBY5qtrqmYSTExtAZ1EW37jdWO6anY/3Hw60GtrPBA1s/Wy7t6B8TrgiV+y89/ACVaJZmZ0e865HvNufcV0ip42FRjwaflICHI4bloDsMk2q3FuN82BLIc2WuM4VY443VJ2fjo1uV70jL3s5b2pmzuZVjSsDVOk9CMFUuzfXJhH8zw+b3w2xJT7dwx7jsQIjOuhSOZyAb8P8OGNp78UI0smeFzwzCuGA30g71KrVfylYqmH7xfUqrtc/k22DdZlall9GqV8DWD6B1hoKRmE8zIlBms1S2iTG92nxblgG0dFgerV1AgFcXjsKoagTKxn0jVY183D3xTmg8jwoEXwFjVk6SMwDcnX4x0Q2vMYegATut9R5W7QeAOKWZ2lRWGjDpsikRqDnb1o/YXSGELdEWXJ9Hf5ys4KMlSQz+fNYd8/heg0dhqUbBldPcM/25I8=
